BEGIN;

INSERT INTO career_questions (
  id, stage, section, trait, purpose, text,
  degrees, branches, skills, goals, tags, priority
)
VALUES
(
  'graduate_ece_software_vs_core_01',
  'graduate',
  'career-discriminator',
  'software',
  'discriminator',
  'Would you prefer building software systems over working directly with electronic hardware?',
  ARRAY['B.Tech / B.E.'],
  ARRAY['ece','electronics','electronics and communication','electronics and communication engineering'],
  ARRAY[]::text[],
  ARRAY['get first job','first job','career switch'],
  ARRAY['ece','software','electronics','career-direction'],
  1
),
(
  'graduate_ece_embedded_01',
  'graduate',
  'career-discriminator',
  'embedded',
  'discriminator',
  'I would enjoy working with microcontrollers, sensors, embedded systems or IoT devices.',
  ARRAY['B.Tech / B.E.'],
  ARRAY['ece','electronics','electronics and communication','electronics and communication engineering'],
  ARRAY[]::text[],
  ARRAY['get first job','first job','career switch'],
  ARRAY['ece','embedded','iot','electronics'],
  1
),
(
  'graduate_ece_vlsi_01',
  'graduate',
  'career-discriminator',
  'vlsi',
  'discriminator',
  'I would enjoy learning digital design, chip design or semiconductor verification in depth.',
  ARRAY['B.Tech / B.E.'],
  ARRAY['ece','electronics','electronics and communication','electronics and communication engineering'],
  ARRAY[]::text[],
  ARRAY['get first job','first job','higher studies'],
  ARRAY['ece','vlsi','semiconductor'],
  1
),
(
  'graduate_software_build_01',
  'graduate',
  'professional-direction',
  'software',
  'measurement',
  'I enjoy turning ideas into working software, apps, websites or automation.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['programming','web development','app development'],
  ARRAY[]::text[],
  ARRAY['software','development'],
  2
),
(
  'graduate_data_analysis_01',
  'graduate',
  'professional-direction',
  'data',
  'measurement',
  'I enjoy finding patterns in data, comparing evidence and explaining what the numbers mean.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['data analysis','programming'],
  ARRAY[]::text[],
  ARRAY['data','analytics'],
  2
),
(
  'graduate_ai_01',
  'graduate',
  'professional-direction',
  'ai',
  'measurement',
  'I would enjoy learning how machine-learning systems are trained, evaluated and improved.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['ai machine learning','programming','data analysis'],
  ARRAY[]::text[],
  ARRAY['ai','machine learning'],
  2
),
(
  'graduate_analytical_01',
  'graduate',
  'strength',
  'analytical',
  'measurement',
  'I enjoy breaking a difficult problem into smaller parts and testing possible solutions logically.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['analytical','problem-solving'],
  2
),
(
  'graduate_communication_01',
  'graduate',
  'strength',
  'communication',
  'measurement',
  'I am comfortable explaining an idea clearly to people with different levels of technical knowledge.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['communication','people'],
  2
),
(
  'graduate_management_01',
  'graduate',
  'professional-direction',
  'management',
  'measurement',
  'I would enjoy coordinating people, priorities and decisions more than specialising deeply in one technical area.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['management','leadership'],
  2
),
(
  'graduate_hands_on_01',
  'graduate',
  'work-preference',
  'handsOn',
  'measurement',
  'I prefer work where I can build, test, operate or troubleshoot real systems rather than only analyse them on a screen.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['hands-on','field-work'],
  3
),
(
  'graduate_stability_01',
  'graduate',
  'career-values',
  'stability',
  'measurement',
  'Long-term job stability is one of my highest career priorities.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['stability','career-values'],
  3
),
(
  'graduate_income_01',
  'graduate',
  'career-values',
  'income',
  'measurement',
  'I am willing to handle a steeper learning curve if it significantly improves long-term earning potential.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['income','growth'],
  3
),
(
  'graduate_autonomy_01',
  'graduate',
  'career-values',
  'autonomy',
  'measurement',
  'I value having freedom to decide how I solve problems and organise my work.',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['autonomy','career-values'],
  3
),
(
  'college_ece_software_vs_core_01',
  'college',
  'career-discriminator',
  'software',
  'discriminator',
  'Would you prefer building software systems over working directly with electronic hardware?',
  ARRAY['B.Tech / B.E.'],
  ARRAY['ece','electronics','electronics and communication','electronics and communication engineering'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['ece','software','electronics','career-direction'],
  1
),
(
  'college_ece_embedded_01',
  'college',
  'career-discriminator',
  'embedded',
  'discriminator',
  'I would enjoy working with microcontrollers, sensors, embedded systems or IoT devices.',
  ARRAY['B.Tech / B.E.'],
  ARRAY['ece','electronics','electronics and communication','electronics and communication engineering'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['ece','embedded','iot'],
  1
),
(
  'college_ece_vlsi_01',
  'college',
  'career-discriminator',
  'vlsi',
  'discriminator',
  'I would enjoy learning digital design, chip design or semiconductor verification in depth.',
  ARRAY['B.Tech / B.E.'],
  ARRAY['ece','electronics','electronics and communication','electronics and communication engineering'],
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY['ece','vlsi','semiconductor'],
  1
)
ON CONFLICT (id) DO UPDATE SET
  stage = EXCLUDED.stage,
  section = EXCLUDED.section,
  trait = EXCLUDED.trait,
  purpose = EXCLUDED.purpose,
  text = EXCLUDED.text,
  degrees = EXCLUDED.degrees,
  branches = EXCLUDED.branches,
  skills = EXCLUDED.skills,
  goals = EXCLUDED.goals,
  tags = EXCLUDED.tags,
  priority = EXCLUDED.priority,
  active = TRUE,
  updated_at = NOW();

COMMIT;
